plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Backup_Data\\Enoch\\affiliate-website\\FirebsaeAuth"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]