plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "C:\\Backup_Data\\Enoch\\affiliate-website\\FirebsaeAuth"
publishOrigin = "ui"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/#invite_token=:token"
to = "/signup.html#invite_token=:token"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/#confirmation_token=:token"
to = "/signup.html#confirmation_token=:token"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/#recovery_token=:token"
to = "/signup.html#recovery_token=:token"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/admin/callback"
to = "/admin/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]